# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Set permissions
RUN chmod +x node_modules/.bin/react-scripts

# Start development server
CMD ["npm", "start"]